export const errorsConfig = {
  401: 'Không xác thực',
  403: 'Bị cấm',
  404: 'Không có sẵn',
  405: 'Phương thức không được hỗ trợ',
  406: 'Not Accessible',
  409: 'Xung đột',
  415: 'Không hỗ trợ định dạng media',
  422: 'Unprocessable Entity',
  429: 'Quá nhiều request',
  500: 'Lỗi Server',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
  1001: 'Không có người dùng này',
  1002: 'Email đã được sử dụng',
  1003: 'Email không hợp lệ',
  1004: 'Họ phải từ 2 - 40 ký tự',
  1005: 'UserID không hợp lệ',
  1006: 'Tên phải từ 2- 40 ký tự',
  1007: 'Tên đăng nhập và mật khẩu không được để trống',
  1008: 'Tên đăng nhập đã tồn tại',
  1009: 'Gõ ít nhất 3 ký tự để tìm kiếm',
  1012: 'Tên đăng nhập phải từ 2 - 40 ký tự',
  1500: 'Lỗi tạo người dùng',
  1501: 'Lỗi lấy dữ liệu người dùng (list)',
  1502: 'error while reading the application user',
  1503: 'error while creating the application user session',
  1504: 'error while deleting session',
  1505: 'error while reading the application user session',
  1506: 'error while deleting all session',
  1507: 'error while updating the application user session',
  1508: 'error while updating the application user',
  1509: 'UserID không tồn tại',
  2000: 'connection already exists',
  2001: 'connection not found',
  2002: 'unexpected connection type',
  2003: 'user is connecting with itself',
  2004: 'users are not connected',
  2500: 'error while connecting the users',
  2501: 'error while creating the connection',
  2502: 'error while reading the connection',
  2503: 'error while updating the connection',
  2504: 'error while retrieving list of followers',
  2505: 'error while retrieving list of following',
  2506: 'error while retrieving list of friends',
  3000: 'you must specify either a radius or a how many nearest events you want',
  3001: 'Location radius can\'t be smaller than 2 meters',
  3002: 'event id is not valid',
  3003: 'event id is already set',
  3004: 'event visibility is invalid',
  3005: 'event visibility is missing',
  3006: 'near events limits not within accepted bounds',
  3007: 'event not found',
  3008: 'type must be between 1 and 30 characters',
  3500: 'error while saving the event',
  3501: 'error while reading the event',
  3502: 'failed to read the events',
  3503: 'error while updating the event',
  3504: 'event is missing ID',
  4001: 'Lỗi xác thực',
  4002: 'both username and email are specified',
  4003: 'Tên đăng nhập và mật khẩu không được để trống',
  4006: 'error while reading application credentials',
  4007: 'error while reading user credentials',
  4008: 'invalid email address',
  4009: 'authorization method not supported',
  4010: 'Mật khẩu không được bỏ trống',
  4011: 'Vui lòng chọn mật khẩu khác',
  4012: 'session token mismatch',
  4013: 'session token missing from request',
  5000: 'image url is not valid',
  5001: 'malformed json received',
  5002: 'User-Agent header must be set',
  5003: 'Content-Length header is invalid',
  5004: 'Content-Length header missing',
  5005: 'Content-Length header size mismatch',
  5006: 'Content-Type header mismatch',
  5007: 'Content-Type header empty',
  5009: 'No known search terms supplied',
  5010: 'Invalid float number',
  5011: 'Payload too big',
  5012: 'Empty request body',
  'UserIsNotExists': 'Tài khoản không tồn tại trong hệ thống'
};
